import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import PromptInput from "~/components/PromptInput";

const Main: NextPage = () => {


  return (
    <>
      <Head>
        <title>Albaab</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col pt-2 items-start justify-center bg-slate-100">
        <Link className="ml-10" href="/">Back</Link>
        <div className="flex flex-col w-full items-center justify-center gap-2 px-4 py-16 ">
          <div className="font-righteous text-6xl">
            AI-Daleel
          </div>
          <div className="text-center">
            AI-powered al-Quran daleel search
          </div>
          <div className="mt-10 md:p-10 w-full md:w-2/3 flex flex-col items-center">
              <PromptInput/>
          </div>
        </div>
      </main>
    </>
  );
};

export default Main;
